package gacha

const (
	GACHA_MODE_NORMAL       = 1
	GACHA_MODE_THREESTARSUP = 2
	GACHA_MODE_UPANDTHREES  = 3
	GACHA_MODE_REPLICA      = 4
)

const (
	TEST_CNT = 1000000
)

const (
	PIECES_3STARS = 50
	PIECES_2STARS = 10
	PIECES_1STARS = 1
)

const (
	BONUS_1_PIGPIECES  = 5
	BONUS_1_CHARPIECES = 40
	BONUS_1_HEARTBREAK = 5

	BONUS_2_PIGPIECES  = 5
	BONUS_2_CHARPIECES = 20
	BONUS_2_HEARTBREAK = 3

	BONUS_3_PIGPIECES  = 1
	BONUS_3_CHARPIECES = 5
	BONUS_3_HEARTBREAK = 3

	BONUS_4_PIGPIECES  = 1
	BONUS_4_CHARPIECES = 1
	BONUS_4_HEARTBREAK = 2

	BONUS_5_PIGPIECES  = 1
	BONUS_5_CHARPIECES = 0
	BONUS_5_HEARTBREAK = 1

	BONUS_6_PIGPIECES  = 1
	BONUS_6_CHARPIECES = 0
	BONUS_6_HEARTBREAK = 0
)
